var express = require('express');
var app = express();
var path = require('path');
var bodyParser = require('body-parser');

const { response } = require('express');
const port = 3000;
app.use(express.static(path.join(__dirname)));
app.use(
    bodyParser.urlencoded({
      extended: true
    })
  );

  var questions = ["what is intrail separation", "how to obtain a license file", "what is Viewer Light"];
  var answers = [
  {q: 'what is intrail separation', a: 'TAAM provides two ways of metering aircraft in air - the In-trail model or the Flow Management model. The two are mutually exclusive. With the In-trail model, spacing can be enforced as a time or distance interval, on specified routes and / or at selected waypoints. The required separation can be specified from the "Intrail Separation Details" dialog for individual waypoints, see Chapter 2: Data Input And Management Tools > Intrail Separation Details and in the same chapter, Intrail Separation Details of the TAAM Reference Manual.'}, 
  {q: 'how to obtain a license file', a: 'From 2013.4, a new tool TAAM License Server Details Generation Tool has been added to TAAM to gather machine details needed by TAAM support to create a new license.The tool is available from the License -> Server Details menu. It allows single click generation of details required for generating a license.The tool is also available as an executable named as lmServerDetail.exe.When the FlexLM license server is installed, the executable is available from the FlexLM license server installation directory, by default: C:\Program Files\FLEXnet Publisher\License Server Manager v11.13.0. The tool asks the user whether the machine is a virtual server or not and then proceeds to generate a server details log file. The generated file can then be attached to a “TAAM License” request via the TAAM Support Helpdesk (available from https://taam.jeppesen.com/helpdesk. A new account will need to be created if you or your organisation have not already created an account). A Knowledge Base article regarding access and usage of the TAAM Support Helpdesk is available from the TAAM Knowledge Base. TAAM Support will use the lmServerDetail.log file to generate and attach the generated license file to the Support Helpdesk request. The folder in which the file is stored is automatically opened to allow for easy attachment of the file to the Support Helpdesk request. If the license host machine is not the same machine on which TAAM is to be installed, the FlexLM License server software should be installed on the host machine.The license server details should be extracted from the host machine. Note:TAAM support can only generate license files generated by this executable tool. It is no longer required to run commands via the windows command prompt to generate license server details. As usual, those with dongle licenses do not need to generate license host details as any license host information is tied to the dongle'},
  {q: 'what is Viewer Light', a: 'The TAAM (Total Airspace and Airport Modeller) Viewer Light is an application designed to replay a recorded TAAM simulation. The recording is rendered on a graphics canvas that allows for: -3D or 2D rendering of the recorded simulation. -Manipulations of the view by displaying or not displaying simulation infrastructure, and saving such settings as display configurations for future retrieval. -Viewing the recording at different zoom or angle levels, and saving these views as camera views for future retrieval.'}
  ];
app.get('/', (req, res) => res.sendFile(path.join(__dirname, 'supportsite.html')));
app.get('/chat', (req, res) => res.sendFile(path.join(__dirname, 'chatbot.html')));
app.post('/fetchAnswer', (req, res)=>{
    
 for(let i = 0; i < questions.length; i++){
     if(req.body.question == questions[i]){
           for(let k = 0; k < answers.length; k++){
             if(req.body.question == answers[k].q){
                res.send({'yourquestion': req.body.question, 'answer': answers[k].a});
    } 
         }
     }     
 }
}
)


app.listen(3000, ()=>{
    console.log('ready to rock and roll!')
})